# taking_file_input


In [5]:
import sys
import numpy as np
import pandas as pd

In [74]:
rect = pd.read_csv("M1_test2.csv")
print ("All values")
print(rect.values)

All values
[[  0   4  65  69]
 [  0  68  65 137]
 [ 64   4 329  69]
 [  0 216  65 285]
 [  0 284  65 349]
 [ 64 284 329 349]
 [120 128 349 225]
 [440   0 529 141]
 [440 212 529 353]
 [620 128 849 225]
 [644   4 905  69]
 [904   4 969  69]
 [904  68 969 137]
 [644 284 905 349]
 [904 216 969 285]
 [904 284 969 349]]


In [75]:
print("Only one row")
print(rect.values[0])

Only one row
[ 0  4 65 69]


In [78]:
x0=rect.values[0,0]
y0=rect.values[0,1]
x1=rect.values[0,2]
y1=rect.values[0,3]

In [ ]:
for( x = myMax(0,x0) ; x<myMin(nx-1,x1); x++) {
	for( y = myMax(0,y0); y<myMin(ny-1,y1); y++) {
	  imgpbo[nx*y + x] = c;

In [105]:
arr=[]
for x in range (max(0,x0),x1):
        for y in range (y0,y1):
            arr.append(255)
arr=np.asarray(arr)
print(arr)

[255 255 255 ... 255 255 255]


In [107]:
arr.itemsize


8

In [108]:
def draw_rect(rect):
    for i in rect:
        x0=rect[i,0]

In [110]:
draw_rect(rect.values[0])

IndexError: too many indices for array

# accessing each element


In [62]:
a=np.array([[10,56],[323,412]])
a

array([[ 10,  56],
       [323, 412]])

In [63]:
print(a[0,0])
print(a[0,1])
print(a[1,0])
print(a[1,1])


10
56
323
412
