In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
t=np.random.randint(0,10,(5,10))
np.savetxt("bla.csv", t, delimiter=",")

In [79]:
# exucute function
def execute(x):
    t1=x[0]+x[5]
    t2 = x[2]*x[3]
    return t1,t2

# start

In [80]:
df=pd.read_csv('bla.csv',header = None)
df

0    1    2    3    4    5    6    7    8    9
0  9.0  3.0  5.0  8.0  0.0  7.0  4.0  3.0  9.0  0.0
1  3.0  2.0  1.0  5.0  3.0  2.0  3.0  8.0  6.0  9.0
2  1.0  8.0  8.0  8.0  3.0  9.0  1.0  1.0  8.0  5.0
3  7.0  0.0  6.0  0.0  0.0  5.0  4.0  9.0  4.0  4.0
4  9.0  5.0  8.0  9.0  2.0  9.0  1.0  7.0  3.0  1.0

In [81]:
for i in df.values:
    print(i)

[9. 3. 5. 8. 0. 7. 4. 3. 9. 0.]
[3. 2. 1. 5. 3. 2. 3. 8. 6. 9.]
[1. 8. 8. 8. 3. 9. 1. 1. 8. 5.]
[7. 0. 6. 0. 0. 5. 4. 9. 4. 4.]
[9. 5. 8. 9. 2. 9. 1. 7. 3. 1.]


# basic python

In [82]:
arr_basic=[]
for i in df.values:
    t1,t2=execute(i)
    arr_basic.append([t1,t2])

In [83]:
arr_basic

[[16.0, 40.0], [5.0, 5.0], [10.0, 64.0], [12.0, 0.0], [18.0, 72.0]]

In [84]:
arr_basic[0]

[16.0, 40.0]

# Numpy Array

In [85]:
#append korar por numpy array na banaile age theke hishab kore rakhte hobe size ki hobe
#then oi bhabe agaite hobe

In [86]:
len(df.values)  # execute er out put size = 2
# shutorang array size hobe 5,2

5

In [112]:
f=open("kernel0.txt",'r')
t=f.readline()
f.close()

In [95]:
#10 ta row in a matrix

In [ ]:
for i in range(10):

In [98]:
t

'0000 0023 0000 0023 0000 0002 064a cd08\n'

In [106]:
t1=t.split(' ')
t1

['0000', '0023', '0000', '0023', '0000', '0002', '064a', 'cd08\n']

In [111]:
i = int(t1[7], 16)
i

52488

In [131]:
t1

['0000', '0000', '0000', '0000', 'b628', '8dc8', 'a50d', '47db\n']

In [201]:
def str_hexa_to_int(t1):
    t1=t1.split(' ')
    t1_arr=[]
    for i in t1:
        t1_arr.append(int(i, 16))
    return t1_arr

In [133]:
t1_arr

[0, 0, 0, 0, 46632, 36296, 42253, 18395]

In [130]:
#over whelming
[int(t1[i], 16) for i in range(len(t1))]

[0, 0, 0, 0, 46632, 36296, 42253, 18395]

In [202]:
f=open("kernel0.txt",'r')


In [203]:
t1=f.readline()
t1

'0000 0023 0000 0023 0000 0002 064a cd08\n'

In [204]:
str_hexa_to_int(t1)

[0, 35, 0, 35, 0, 2, 1610, 52488]

In [ ]:
t1.split(' ')
t1_arr=[]
for i in t1:
    t1_arr.append(int(i, 16))

In [128]:
t1=t.split(' ')
t1

['0000', '0000', '0000', '0000', 'b628', '8dc8', 'a50d', '47db\n']

In [207]:
def str_hexa_to_int(t1):
    t1=t1.split(' ')
    t1_arr=[]
    for i in t1:
        t1_arr.append(int(i, 16))
    return t1_arr

In [208]:
i = int(t1[7], 16)

In [209]:
bigArr=[]
f=open("kernel0.txt",'r')
for i in range(10):
    t=f.readline()
    bigArr.append(str_hexa_to_int(t))
    
    

In [210]:
bigArr

[[0, 35, 0, 35, 0, 2, 1610, 52488],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 46632, 36296, 42253, 18395]]

In [212]:
np.save('big',bigArr)

In [118]:
# f=open('fh0.bin','r')
# f.readline()

In [213]:
np.load('big.npy')

array([[    0,    35,     0,    35,     0,     2,  1610, 52488],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0, 46632, 36296, 42253, 18395]])

# Dictionary

In [87]:
dict({'ali':6,
     'anika':7,
     'bla':8})

{'ali': 6, 'anika': 7, 'bla': 8}

In [88]:
dict

dict

In [89]:
my_dict=dict({})
c=1
for i in df.values:
    t1,t2=execute(i)
    my_dict['rect_'+str(c)]=np.array([t1,t2])
    c+=1
my_dict   

{'rect_1': array([16., 40.]),
 'rect_2': array([5., 5.]),
 'rect_3': array([10., 64.]),
 'rect_4': array([12.,  0.]),
 'rect_5': array([18., 72.])}

In [90]:
for i in range(1,len(my_dict)+1):
    print(my_dict['rect_'+str(i)])

[16. 40.]
[5. 5.]
[10. 64.]
[12.  0.]
[18. 72.]


In [76]:
my_dict['rect_4'][0]

12.0

In [43]:
dict({})

{}

In [55]:
x=dict({})

In [56]:
x['4']=6

In [63]:
x['ali']='anika'

In [64]:
x

{'4': 6, 'ali': 'anika'}

In [66]:
x.keys()

dict_keys(['4', 'ali'])

In [67]:
x.values()

dict_values([6, 'anika'])

In [52]:
d = {'key':'value'}
print(d)
# {'key': 'value'}
d['mynewkey'] = 'mynewvalue'
print(d)
# {'mynewkey': 'mynewvalue', 'key': 'value'}

{'key': 'value'}
{'key': 'value', 'mynewkey': 'mynewvalue'}


In [37]:
df.values

array([[9., 3., 5., 8., 0., 7., 4., 3., 9., 0.],
       [3., 2., 1., 5., 3., 2., 3., 8., 6., 9.],
       [1., 8., 8., 8., 3., 9., 1., 1., 8., 5.],
       [7., 0., 6., 0., 0., 5., 4., 9., 4., 4.],
       [9., 5., 8., 9., 2., 9., 1., 7., 3., 1.]])

In [24]:
(4,8)

(4, 8)

In [25]:
t=(6,7,8)

In [27]:
type(t)

tuple

In [28]:
t[0]=0

TypeError: 'tuple' object does not support item assignment