In [3]:
import numpy as np


In [4]:
ar = [7,'ali',9.8]
#numpy version
ar_np = np.array(ar)
a=[1,2,"hello","world",1.20]
print(a)

[1, 2, 'hello', 'world', 1.2]


In [9]:
a[3]+' '+a[3]

'world world'

In [11]:
a[0]+a[1]

3

In [12]:
[1,2,3]+[3,4,5]

[1, 2, 3, 3, 4, 5]

In [13]:
np.array([1,2,3])+np.array([3,4,5])

array([4, 6, 8])

In [5]:

ar_np

array(['7', 'ali', '9.8'], dtype='<U21')

### No concatenation

In [6]:
[7,8,9]+[4,5,6]

[7, 8, 9, 4, 5, 6]

In [7]:
np.array([7,8,9])+np.array([4,5,6])

array([11, 13, 15])

In [8]:
5*np.array([1,2,3])

array([ 5, 10, 15])

In [10]:
5*np.array([[1,2,3],[4,5,6]])

array([[ 5, 10, 15],
       [20, 25, 30]])

In [12]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.array([10,100,1000])*np.array([[1,2,3],[4,5,6]])

array([[  10,  200, 3000],
       [  40,  500, 6000]])

In [19]:
np.array([[10],[100]])*np.array([[1,2,3],[4,5,6]])

array([[ 10,  20,  30],
       [400, 500, 600]])

In [21]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b=np.array([[1,2],[3,4],[5,6],[7,8]])
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [24]:
np.matmul(b,a)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51],
       [39, 54, 69]])

In [26]:
np.arange(6,16)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
a=np.array([3,2,5,3,2,4,5,3,2,5,3,4,2,5,3,4,5,3,4,5,3,4,5,3,4])
a.shape

(25,)

In [36]:
a_1=a.reshape(1,25)
a_1

array([[3, 2, 5, 3, 2, 4, 5, 3, 2, 5, 3, 4, 2, 5, 3, 4, 5, 3, 4, 5, 3, 4,
        5, 3, 4]])

In [37]:
a_1.shape

(1, 25)

In [38]:
a_2=a.reshape(5,5)
a_2

array([[3, 2, 5, 3, 2],
       [4, 5, 3, 2, 5],
       [3, 4, 2, 5, 3],
       [4, 5, 3, 4, 5],
       [3, 4, 5, 3, 4]])

In [39]:
a_2.shape

(5, 5)

In [40]:
a_2.size

25

# welcome for loop

In [42]:
#a = [1,2,3,4,5,6]
b = [10,20,30,40,50,60]

In [51]:
new_b = []
for i in b:
    temp = i+2
    new_b.append(temp)
    

In [45]:
new_b

[12, 22, 32, 42, 52, 62]

In [46]:
new_b

[12, 22, 32, 42, 52, 62]

In [47]:
del new_b

In [48]:
new_b

NameError: name 'new_b' is not defined

In [53]:
new_b_np=np.array(new_b)
new_b_np

array([12, 22, 32, 42, 52, 62])

In [57]:
t=new_b_np.shape
del new_b_np
new_b_np = np.zeros(t)
new_b_np

array([0., 0., 0., 0., 0., 0.])

In [49]:
np.empty(5)

array([4.65915017e-310, 6.94746458e-310, 0.00000000e+000, 0.00000000e+000,
       3.42109690e+126])

# say bye to For Loop

In [58]:
a = [1,2,3,4,5,6]
b = [10,20,30,40,50,60]

In [60]:
a_b =[]
for i in range(len(a)):
    t=a[i]*b[i]
    a_b.append(t)

In [61]:
a_b

[10, 40, 90, 160, 250, 360]

In [62]:
np.array(a)*np.array(b)

array([ 10,  40,  90, 160, 250, 360])

In [63]:
x=np.array([5,3,1,5,3,5,7,9,4,3,2,5])

In [64]:
np.max(x)

9

In [65]:
np.argmax(x)

7

In [66]:
x[2:5]

array([1, 5, 3])

In [73]:
x=np.arange(1,26).reshape(5,5)

In [74]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [76]:
index=x%3==0
index

array([[False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False]])

In [77]:
x[index]

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
np.array